title: "SerialReads"
description: "Deep-dive reading log & research notes"

remote_theme: pages-themes/primer

markdown: CommonMarkGhPages
plugins:
  - jekyll-remote-theme

collections:
  quizzes:
    output: true
    permalink: /quiz/:name/        # → /quiz/<filename>/
  flashcards:
    output: true
    permalink: /flashcards/:title/ # → /flashcards/<deck-title>/
