title: "SerialReads"
description: "Deep-dive reading log & research notes"

remote_theme: pages-themes/primer

markdown: CommonMarkGhPages
plugins:
  - jekyll-remote-theme

collections:
  quizzes:
    output: true
    permalink: /quiz/:name/        # → /quiz/<filename>/
  flashcards:
    output: true
    permalink: /flashcards/:title/ # → /flashcards/<deck-title>/
  matchcards:                # ← new
    output: true
    permalink: /match/:title/

# ▼ NEW – site-wide links
navigation:
  - title: Home
    url: /
  - title: Tags
    url: /tags/
  - title: Quizzes
    url: /quiz/
  - title: Flashcards
    url: /flashcards/
  - title: Matching
    url: /match/    