# _config.yml
title: "SerialReads"
description: "Deep-dive reading log & research notes"

remote_theme: pages-themes/primer

markdown: CommonMarkGhPages      # ← back to the renderer you started with
plugins:
  - jekyll-remote-theme
