title: "SerialReads"
description: "Deep-dive reading log & research notes"

remote_theme: pages-themes/primer          # clean GitHub Pages theme

markdown: kramdown              # ← switch renderer
plugins:
  - jekyll-remote-theme
