title: "SerialReads"
description: "Deep-dive reading log & research notes"

# either of these works – pick ONE
remote_theme: pages-themes/primer          # no version pin
# remote_theme: pages-themes/primer@v0.6.0 # explicit, valid tag

plugins:
  - jekyll-remote-theme
